name: rl_models
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - python=3.8.13
  - python_abi=3.8
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - cachetools==5.1.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - cloudpickle==2.1.0
    - cycler==0.11.0
    - cython==0.29.30
    - fasteners==0.15
    - flatbuffers==1.12
    - fonttools==4.33.3
    - free-mujoco-py==2.1.6
    - gast==0.4.0
    - glfw==1.12.0
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.3
    - gym==0.23.1
    - gym-notices==0.0.6
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.19.2
    - importlib-metadata==4.11.3
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - libclang==14.0.1
    - llvmlite==0.36.0
    - markdown==3.3.7
    - matplotlib==3.5.2
    - monotonic==1.6
    - mujoco-py==2.1.2.14
    - numba==0.53.1
    - numpy==1.22.4
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pillow==9.1.1
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygame==2.1.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - robosuite==1.3.2
    - rsa==4.8
    - scipy==1.8.1
    - six==1.16.0
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.0
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.8.0
# prefix: /home/tony/miniconda3/envs/rl_models
